### ISSUE TITLE
The custom integration 'slack_user' does not have a valid version key

### ISSUE THREAD

**Issue by davidolrik** [GeorgeSG/ha-slack-user#4]
The custom integration 'slack_user' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by GeorgeSG** [comment]
Oh, I forgot about that, thank you! Released version `0.3.0` that should fix the issue.
