### ISSUE TITLE
Allow set DND and away

### ISSUE THREAD

**Issue by polcape** [GeorgeSG/ha-slack-user#6]
Hi, thanks for the component. It's very very useful!!

I would like to propose a feature. It would be nice if the component will allow setting 
  - the DND feature (to stop notification)
  - the presence (set to auto or away)

Thanks

**Comment by michaellunzer** [comment]
+1 love this idea. I'd like to scan an RFID tag to "log in" to work at my home office and set my slack presence to online in the morning 😎

**Comment by GeorgeSG** [comment]
Implemented in release [v0.5.0](https://github.com/GeorgeSG/ha-slack-user/releases/tag/v0.5.0)! Thanks for the suggestion!
