### ISSUE TITLE
Huddle attributes

### ISSUE THREAD

**Issue by samhh** [GeorgeSG/ha-slack-user#8]
Thanks for the integration!

By the looks of it [here](https://api.slack.com/methods/users.profile.get) the API should be exposing a couple of properties pertaining to huddles, including `huddle_state`. Any chance we could expose them to HA?

**Comment by GeorgeSG** [comment]
Implemented in release [v0.5.0](https://github.com/GeorgeSG/ha-slack-user/releases/tag/v0.5.0)! Thanks for the suggestion!
