### ISSUE TITLE
[Feature request] Getting status expiration

### ISSUE THREAD

**Issue by mbrammer** [GeorgeSG/ha-slack-user#9]
When setting a status, I would like to restore a maybe existing current status. For that I save the status text and emoji inside a helper.
If you could add the current expiration datetime to the user sensor, I could also save and restore the expiration.

**Comment by GeorgeSG** [comment]
Implemented in release [v0.5.0](https://github.com/GeorgeSG/ha-slack-user/releases/tag/v0.5.0)! Thanks for the suggestion!
